package presets

import "sort"

var Map = map[string]string{
	"LJR":          `[{"name":"ActualIn.T_Engine","method":2,"value":3469,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"ActualIn.T_AirInlet","method":2,"value":3470,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"IgnProt.fi_Offset","method":2,"value":3045,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.fi_Ignition","method":2,"value":3686,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.PWM_BoostCntrl","method":2,"value":3645,"type":33,"length":2,"correctionfactor":0.1,"group":"%"},{"name":"ActualIn.p_AirInlet","method":2,"value":3472,"type":33,"length":2,"correctionfactor":0.001,"group":"Boost"},{"name":"In.p_AirBefThrottle","method":2,"value":3395,"type":33,"length":2,"correctionfactor":0.001,"group":"Boost"},{"name":"MAF.m_AirInlet","method":2,"value":452,"type":32,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"m_Request","method":2,"value":59,"type":0,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"ECMStat.ST_ActiveAirDem","method":2,"value":3754,"type":36,"length":1,"correctionfactor":1,"group":"Limiters"}]`,
	"JSH":          `[{"name":"ActualIn.T_Engine","method":2,"value":3469,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"ActualIn.T_AirInlet","method":2,"value":3470,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"IgnProt.fi_Offset","method":2,"value":3045,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.fi_Ignition","method":2,"value":3686,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.PWM_BoostCntrl","method":2,"value":3645,"type":33,"length":2,"correctionfactor":0.1,"group":"%"},{"name":"ActualIn.p_AirInlet","method":2,"value":3472,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"In.p_AirBefThrottle","method":2,"value":3395,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"ECMStat.p_Diff","method":2,"value":3759,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"MAF.m_AirInlet","method":2,"value":452,"type":32,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"m_Request","method":2,"value":59,"type":0,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"ECMStat.ST_ActiveAirDem","method":2,"value":3754,"type":36,"length":1,"correctionfactor":1,"group":"Limiters"}]`,
	"Dash":         `[{"name":"ActualIn.T_Engine","method":2,"value":3469,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"ActualIn.T_AirInlet","method":2,"value":3470,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"IgnProt.fi_Offset","method":2,"value":3045,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.fi_Ignition","method":2,"value":3686,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.PWM_BoostCntrl","method":2,"value":3645,"type":33,"length":2,"correctionfactor":0.1,"group":"%"},{"name":"ActualIn.p_AirInlet","method":2,"value":3472,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"In.p_AirBefThrottle","method":2,"value":3395,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"ECMStat.p_Diff","method":2,"value":3759,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"MAF.m_AirInlet","method":2,"value":452,"type":32,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"m_Request","method":2,"value":59,"type":0,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"ECMStat.ST_ActiveAirDem","method":2,"value":3754,"type":36,"length":1,"correctionfactor":1,"group":"Limiters"},{"name":"DisplProt.LambdaScanner","method":2,"value":3316,"type":33,"length":2,"correctionfactor":0.01,"group":"Fuel"},{"name":"Lambda.LambdaInt","method":2,"value":2606,"type":33,"length":2,"correctionfactor":0.01,"group":"Fuel"}]`,
	"Dash OBDLink": `[{"name":"ActualIn.T_Engine","method":2,"value":3469,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"ActualIn.T_AirInlet","method":2,"value":3470,"type":33,"length":2,"correctionfactor":1,"group":"Temperature"},{"name":"IgnProt.fi_Offset","method":2,"value":3045,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.fi_Ignition","method":2,"value":3686,"type":33,"length":2,"correctionfactor":0.1,"group":"Ignition"},{"name":"Out.PWM_BoostCntrl","method":2,"value":3645,"type":33,"length":2,"correctionfactor":0.1,"group":"%"},{"name":"ActualIn.p_AirInlet","method":2,"value":3472,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"In.p_AirBefThrottle","method":2,"value":3395,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"ECMStat.p_Diff","method":2,"value":3759,"type":33,"length":2,"correctionfactor":0.001,"group":"Bar"},{"name":"MAF.m_AirInlet","method":2,"value":452,"type":32,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"m_Request","method":2,"value":59,"type":0,"length":2,"correctionfactor":1,"group":"Air mg/c"},{"name":"ECMStat.ST_ActiveAirDem","method":2,"value":3754,"type":36,"length":1,"correctionfactor":1,"group":"Limiters"},{"name":"DisplProt.LambdaScanner","method":2,"value":3316,"type":33,"length":2,"correctionfactor":0.01,"group":"Fuel"},{"name":"Lambda.LambdaInt","method":2,"value":2606,"type":33,"length":2,"correctionfactor":0.01,"group":"Fuel"},{"name":"ActualIn.n_Engine","method":2,"value":3462,"type":33,"length":2,"unit":"Value","correctionfactor":1,"group":"Rpm"},{"name":"Out.X_AccPedal","method":2,"value":3672,"type":33,"length":2,"unit":"%","correctionfactor":0.1,"group":"%"},{"name":"In.v_Vehicle","method":2,"value":3409,"type":33,"length":2,"unit":"Km/h","correctionfactor":0.1,"group":"Km/h"}]`,
	"Dash T8":      `[{"name":"ActualIn.T_Engine","method":2,"value":4193,"type":1,"length":2,"unit":"Value","correctionfactor":1},{"name":"ActualIn.T_AirInlet","method":2,"value":4209,"type":1,"length":2,"unit":"Value","correctionfactor":1},{"name":"IgnMastProt.fi_Offset","method":2,"value":3337,"type":1,"length":2,"unit":"Value","correctionfactor":0.1},{"name":"Out.fi_Ignition","method":2,"value":4806,"type":1,"length":2,"unit":"° BTDC","correctionfactor":0.1},{"name":"Out.PWM_BoostCntrl","method":2,"value":4779,"type":1,"length":2,"unit":"%","correctionfactor":0.1},{"name":"In.p_AirInlet","method":2,"value":4072,"type":1,"length":2,"unit":"Value","correctionfactor":0.001},{"name":"ActualIn.p_AirBefThrottle","method":2,"value":4197,"type":1,"length":2,"unit":"Value","correctionfactor":0.001},{"name":"MAF.m_AirInlet","method":2,"value":391,"type":1,"length":2,"unit":"Mg/c","correctionfactor":1},{"name":"AirMassMast.m_Request","method":2,"value":267,"type":1,"length":2,"unit":"Value","correctionfactor":1},{"name":"ECMStat.ST_ActiveAirDem","method":2,"value":4916,"type":4,"length":1,"unit":"Value","correctionfactor":1},{"name":"Lambda.LambdaInt","method":2,"value":2801,"type":1,"length":2,"unit":"Value","correctionfactor":0.01},{"name":"ActualIn.n_Engine","method":2,"value":4219,"type":1,"length":2,"unit":"Value","correctionfactor":1},{"name":"Out.X_AccPos","method":2,"value":4714,"type":1,"length":2,"unit":"Value","correctionfactor":0.1},{"name":"In.v_Vehicle","method":2,"value":4092,"type":1,"length":2,"unit":"Km/h","correctionfactor":0.1}]`,
}

func Names() []string {
	var names []string
	for name := range Map {
		names = append(names, name)
	}
	sort.Strings(names)
	return names
}
