$env:PKG_CONFIG_PATH = "C:\vcpkg\packages\libusb_x86-windows\lib\pkgconfig"
$env:CGO_CFLAGS = "-IC:\vcpkg\packages\libusb_x86-windows\include\libusb-1.0"
$env:GOARCH = "386"
$env:CGO_ENABLED = "1"
Invoke-Expression "fyne package -tags combi --release"