package windows

func (mw *MainWindow) t7Menu() []MenuItem {
	return []MenuItem{
		{Name: "Diagnostics", Children: []MenuItem{
			{Name: "DTC Reader", Func: mw.openDTCReader},
			{Name: "J1979", Func: mw.openJ1979},
			{Name: "PI area editor", Func: mw.openPIAreaEditor},
			{Name: "F_KnkDetAdap.FKnkCntMap"},
			{Name: "F_KnkDetAdap.RKnkCntMap"},
			{Name: "KnkDetAdap.KnkCntMap"},
			{Name: "MissfAdap.MissfCntMap"},
		}},
		{Name: "Calibration", Children: []MenuItem{
			{Name: "ESP Calibration", Func: mw.openESPCalibration},
			{Name: "AirCompCal.PressMap"},
			{Name: "AirCtrlCal.map"},
			{Name: "AreaCal.Area"},
			{Name: "AreaCal.Table"},
			{Name: "Ethanol adaption value", Data: "E85.X_EthAct_Tech2"},
			{Name: "MAFCal.m_RedundantAirMap"},
			{Name: "TCompCal.EnrFacE85Tab"},
			{Name: "TCompCal.EnrFacTab"},
			{Name: "VIOSMAFCal.FreqSP"},
			{Name: "VIOSMAFCal.Q_AirInletTab2"},
		}},
		{Name: "Injectors", Children: []MenuItem{
			{Name: "Injector dead time", Data: "InjCorrCal.BattCorrTab"},
			{Name: "Injector dead time (Y)", Data: "InjCorrCal.BattCorrSP"},
			{Name: "Injector constant", Data: "InjCorrCal.InjectorConst"},
		}},
		{Name: "Airmass", Children: []MenuItem{
			{Name: "Pedal request map", Data: "PedalMapCal.m_RequestMap"},
			{Name: "Pedal request airmass (Y)", Data: "TorqueCal.m_PedYSP"},
			{Name: "Air/Torque calibration", Data: "TorqueCal.m_AirTorqMap"},
			{Name: "Air/Torque (X)", Data: "TorqueCal.M_EngXSP"},
			{Name: "Nom. torque map", Data: "TorqueCal.M_NominalMap"},
			{Name: "Nom. torque map (X)", Data: "TorqueCal.m_AirXSP"},
		}},
		{Name: "Fuel", Children: []MenuItem{
			{Name: "Fuel cut", Children: []MenuItem{
				{Name: "FCutCal.ST_Enable"},
				{Name: "FCutCal.FuelFactor"},
				{Name: "FCutCal.n_CombSP (Y)", Data: "FCutCal.n_CombSP"},
			}},
			{Name: "Closed Loop", Children: []MenuItem{
				{Name: "Max load norm", Data: "LambdaCal.MaxLoadNormTab"},
				{Name: "Max load E85", Data: "LambdaCal.MaxLoadE85Tab"},
			}},
			{Name: "TransCal", Children: []MenuItem{
				{Name: "TransCal.ST_Enable"},
				{Name: "TransCal.ST_DecNoLim"},
				{Name: "TransCal.AccRampFac"},
				{Name: "TransCal.DecRampFac"},
				{Name: "TransCal.AccFacMap"},
				{Name: "TransCal.DecFacMap"},
				{Name: "TransCal.RpmSP (Y)", Data: "TransCal.RpmSP"},
				{Name: "TransCal.AccSP (X)", Data: "TransCal.AccSP"},
				{Name: "TransCal.DecSP (X)", Data: "TransCal.DecSP"},
				{Name: "TransCal.RetMul"},
				{Name: "TransCal.AccMul"},
				{Name: "TransCal.RetMulConst"},
				{Name: "TransCal.AccMulConst"},
				{Name: "TransCal.Delay1"},
				{Name: "TransCal.Delay2"},
				{Name: "TransCal.m_TriggMaxTab"},
				{Name: "TransCal.FilterConstAir"},
			}},
			{Name: "VE map", Data: "BFuelCal.Map", Region: "LambdaCal.MaxLoadNormTab"},
			{Name: "Startup / E85 VE map", Data: "BFuelCal.StartMap", Region: "LambdaCal.MaxLoadE85Tab"},
			{Name: "Gas VE map", Data: "BFuelCal.GasMap"},
			{Name: "Enrichment factor during starting", Data: "StartCal.EnrFacTab"},
			{Name: "Enrichment factor during starting E85", Data: "StartCal.EnrFacE85Tab"},
			{Name: "Enable cloosed loop regulation", Data: "LambdaCal.ST_Enable"},
			{Name: "Common for tuning", Data: "AdpFuelCal.T_AdaptLim|E85Cal.ST_Enable|FCutCal.ST_Enable|LambdaCal.ST_Enable|PurgeCal.ST_PurgeEnable|TorqueCal.M_BrakeLimit"},
			{Name: "Injection end angles", Data: "InjAnglCal.Map"},
		}},
		{Name: "Ignition", Children: []MenuItem{
			{Name: "Ignition map", Data: "IgnNormCal.Map", Region: "LambdaCal.MaxLoadNormTab"},
			{Name: "Ignition for E85", Data: "IgnE85Cal.fi_AbsMap", Region: "LambdaCal.MaxLoadE85Tab"},
			{Name: "Ignition for Gas", Data: "IgnNormCal.GasMap"},
			{Name: "Ignition Idle", Data: "IgnIdleCal.fi_IdleMap"},
			{Name: "Ignition Start", Data: "IgnStartCal.fi_StartMap"},
			{Name: "Knock pull map", Data: "IgnKnkCal.IndexMap"},
			{Name: "Max knock pull", Data: "KnkFuelCal.fi_MapMaxOff"},
		}},
		{Name: "Boost", Children: []MenuItem{
			{Name: "Boost regulation overview", Data: "BoostCal.RegMap|BoostCal.PMap|BoostCal.IMap|BoostCal.DMap"},
			{Name: "Boost calibration", Data: "BoostCal.RegMap"},
			{Name: "P factor", Data: "BoostCal.PMap"},
			{Name: "I factor", Data: "BoostCal.IMap"},
			{Name: "D factor", Data: "BoostCal.DMap"},
			{Name: "Boost Temp Compensation", Data: "BoostCal.PWMTempTab"},
			{Name: "Boost Temp Compensation (Y)", Data: "BoostCal.PWMTempSP"},
		}},
		{Name: "Knock", Children: []MenuItem{
			{Name: "Knock enrichment", Data: "KnkFuelCal.EnrichmentMap"},
			{Name: "Knock sensitivity", Data: "KnkDetCal.RefFactorMap"},
		}},
		{Name: "Limiters", Children: []MenuItem{
			{Name: "Manual", Children: []MenuItem{
				{Name: "Airmass (M)", Data: "BstKnkCal.MaxAirmass"},
				{Name: "Engine torque (M)", Data: "TorqueCal.M_EngMaxTab"},
				{Name: "Engine torque for E85 (M)", Data: "TorqueCal.M_EngMaxE85Tab"},
				{Name: "Gear Torque (M)", Data: "TorqueCal.M_ManGearLim"},
				{Name: "Gear Torque (5th)", Data: "TorqueCal.M_5GearLimTab"},
			}},
			{Name: "Automatic", Children: []MenuItem{
				{Name: "Airmass (A)", Data: "BstKnkCal.MaxAirmassAu"},
				{Name: "Engine torque (A)", Data: "TorqueCal.M_EngMaxAutTab"},
				{Name: "Engine torque for E85 (A)", Data: "TorqueCal.M_EngMaxE85TabAut"},
			}},
			{Name: "RPM limiter", Data: "MaxSpdCal.n_EngLimAir"},
			{Name: "Fuel cut", Data: "FCutCal.m_AirInletLimit"},
			{Name: "Speed limiter", Data: "MaxVehicCal.v_MaxSpeed"},
			{Name: "Overboost", Data: "TorqueCal.M_OverBoostTab"},
		}},
		{Name: "Adaption", Children: []MenuItem{
			{Name: "Temp limit for adaption", Data: "AdpFuelCal.T_AdaptLim"},
			{Name: "Fuelcut enabled", Data: "FCutCal.ST_Enable"},
			{Name: "Closed loop regulation", Data: "LambdaCal.ST_Enable"},
			{Name: "Purge enabled", Data: "PurgeCal.ST_PurgeEnable"},
			{Name: "Biopower enabled", Data: "E85Cal.ST_Enable"},
		}},
		{Name: "Myrtilos", Children: []MenuItem{
			{Name: "Register EU0D", Func: mw.openRegisterEU0D},
			{Name: "MyrtilosCal.Launch_DisableSpeed"},
			{Name: "MyrtilosCal.Launch_Ign_fi_Min"},
			{Name: "MyrtilosCal.Launch_RPM"},
			{Name: "MyrtilosCal.Launch_InjFac_at_rpm"},
			{Name: "MyrtilosCal.Launch_PWM_max_at_stand"},
			{Name: "MyrtilosAdap.WBLambda_FeedbackMap"},
			{Name: "MyrtilosAdap.WBLambda_FFMap"},
		}},
	}
}
