package windows

var T8SymbolsTuningOrder = []string{
	"Diagnostics",
	"Airmass",
	"Torque",
	"Injectors",
	"Fuel",
	"Boost",
	"Ignition",
	"Pedal",
}

var T8SymbolsTuning = map[string][]string{
	"Diagnostics": {
		"DTC Reader",
	},
	"Airmass": {
		"Max airmass map (manual)|BstKnkCal.MaxAirmass",
		"Max airmass map (auto)|BstKnkCal.MaxAirmassAu",
		"Airmass Fuelcut|FCutCal.m_AirInletLimit",
		"AirCtrlCal.AirmassLimiter",
		"AirCtrlCal.PRatioMaxTab",
	},
	"Torque": {
		"Nominal torque map|TrqMastCal.Trq_NominalMap",
		"Airmass torque map|TrqMastCal.m_AirTorqMap",
		"Ambient pressure trq limiter|TrqLimCal.Trq_CompressorNoiseRedLimMAP",
		"Trq limit in overboost|TrqLimCal.Trq_OverBoostTab",
		"Trq limit manual 150hp|TrqLimCal.Trq_MaxEngineManTab2",
		"Trq limit manual 175+hp|TrqLimCal.Trq_MaxEngineManTab1",
		"Trq limit auto 150hp|TrqLimCal.Trq_MaxEngineAutTab2",
		"Trq limit auto 175+hp|TrqLimCal.Trq_MaxEngineAutTab1",
		"Manual gear trq limit|TrqLimCal.Trq_ManGear",
		"RPM limiter|MaxEngSpdCal.n_EngLimTab",
		"TrqLimCal.Trq_MaxEngineTab1",
		"TrqLimCal.Trq_MaxEngineTab2",
		"FFTrqCal.FFTrq_MaxEngineTab1",
		"FFTrqCal.FFTrq_MaxEngineTab2",
	},
	"Injectors": {
		"Inj. Constant|InjCorrCal.InjectorConst",
		"Inj. dead time|InjCorrCal.BattCorrTab",
		"Inj. dead time (Y)|InjCorrCal.BattCorrSP",
	},
	"Fuel": {
		"Fuel correction map|BFuelCal.LambdaOneFacMap",
		"Enrichment Petrol|BFuelCal.TempEnrichFacMap",
		"Enrichment E85|FFFuelCal.TempEnrichFacMAP",
		"Knock fuel map|KnkFuelCal.EnrichmentMap",
		"Injection end angle map|InjAnglCal.Map",
		"Jerk enrichment petrol|BFuelCal.m_AirJerkTab",
		"Jerk enrichment Fuelmaster|BFuelCal.JerkEnrichFacTab",
		"PurgeCal.ST_PurgeEnable",
		"LambdaCal.ST_Enable",
		"FCutCal.ST_Enable",
		"FFFuelCal.ST_enable",
		"FuelDynCal.ST_Enable",
		"TCompCal.ST_Enable",
	},
	"Boost": {
		"Boost regulation map|AirCtrlCal.RegMap",
		"P factor|AirCtrlCal.Ppart_BoostMap",
		"I factor|AirCtrlCal.Ipart_BoostMap",
		"D factor|AirCtrlCal.Dpart_BoostMap",
		"AirCtrlCal.ST_BoostEnable",
		"BoostAdapCal.ST_enable",
		"FrompAdapCal.ST_enable",
		"AreaAdapCal.ST_enable",
	},
	"Ignition": {
		"Normal ignition map|IgnAbsCal.fi_NormalMAP",
		"High octane map|IgnAbsCal.fi_highOctanMAP",
		"Low octane map|IgnAbsCal.fi_lowOctanMAP",
		"MBT ignition map|IgnAbsCal.fi_IgnMBTMAP",
		"Fuel cut ignition map|IgnAbsCal.fi_FuelCutMAP",
		"Startup map|IgnAbsCal.fi_StartMAP",
		"IgnAbsCal.ST_EnableOctanMaps",
	},
	"Pedal": {
		"Pedal position map|TrqMastCal.X_AccPedalMAP",
		"Torque request map|PedalMapCal.Trq_RequestMap",
	},
}
