package windows

var T7SymbolsTuningOrder = []string{
	"Diagnostics",
	"Calibration",
	"Injectors",
	"Fuel",
	"Ignition",
	"Airmass",
	"Boost",
	"Knock",
	"Limiters",
	"Adaption",
	"Myrtilos",
}

var T7SymbolsTuning = map[string][]string{
	"Diagnostics": {
		"DTC Reader",
		// "Firmware information",
		"F_KnkDetAdap.FKnkCntMap",
		"F_KnkDetAdap.RKnkCntMap",
		"KnkDetAdap.KnkCntMap",
		"MissfAdap.MissfCntMap",
	},
	"Calibration": {
		"ESP Calibration",
		"AirCompCal.PressMap",
		"Ethanol adaption value|E85.X_EthAct_Tech2",
		"MAFCal.m_RedundantAirMap",
		"TCompCal.EnrFacE85Tab",
		"TCompCal.EnrFacTab",
		"VIOSMAFCal.FreqSP",
		"VIOSMAFCal.Q_AirInletTab2",
	},
	"Injectors": {
		"Injector dead time|InjCorrCal.BattCorrTab",
		"Injector dead time (Y)|InjCorrCal.BattCorrSP",
		"Injector constant|InjCorrCal.InjectorConst",
	},
	"Airmass": {
		"Pedal request map|PedalMapCal.m_RequestMap",
		"Pedal request airmass (Y)|TorqueCal.m_PedYSP",
		"Air/Torque calibration|TorqueCal.m_AirTorqMap",
		"Air/Torque (X)|TorqueCal.M_EngXSP",
		"Nom. torque map|TorqueCal.M_NominalMap",
		"Nom. torque map (X)|TorqueCal.m_AirXSP",
	},
	"Fuel": {
		"VE map|BFuelCal.Map",
		"Startup VE map / E85 VE map|BFuelCal.StartMap",
		"Gas VE map|BFuelCal.GasMap",
		"Enrichment factor during starting|StartCal.EnrFacTab",
		"Enrichment factor during starting E85|StartCal.EnrFacE85Tab",
	},
	"Ignition": {
		"Ignition map|IgnNormCal.Map",
		"Ignition for E85|IgnE85Cal.fi_AbsMap",
		"Ignition for Gas|IgnNormCal.GasMap",
		"Ignition Idle|IgnIdleCal.fi_IdleMap",
		"Ignition Start|IgnStartCal.fi_StartMap",
		"Knock pull map|IgnKnkCal.IndexMap",
		"Max knock pull|KnkFuelCal.fi_MapMaxOff",
	},
	"Boost": {
		"Boost calibration|BoostCal.RegMap",
		"P factor|BoostCal.PMap",
		"I factor|BoostCal.IMap",
		"D factor|BoostCal.DMap",
	},
	"Knock": {
		"Knock enrichment|KnkFuelCal.EnrichmentMap",
		"Knock sensitivity|KnkDetCal.RefFactorMap",
	},
	"Limiters": {
		"Airmass (M)|BstKnkCal.MaxAirmass",
		"Engine torque (M)|TorqueCal.M_EngMaxTab",
		"Engine torque for E85 (M)|TorqueCal.M_EngMaxE85Tab",
		"Gear Torque (M)|TorqueCal.M_ManGearLim",
		"Gear Torque (5th)|TorqueCal.M_5GearLimTab",
		"Airmass (A)|BstKnkCal.MaxAirmassAu",
		"Engine torque (A)|TorqueCal.M_EngMaxAutTab",
		"Engine torque for E85 (A)|TorqueCal.M_EngMaxE85TabAut",
		"RPM limiter|MaxSpdCal.n_EngLimAir",
		"Fuel cut|FCutCal.m_AirInletLimit",
		"Speed limiter|MaxVehicCal.v_MaxSpeed",
		"Overboost|TorqueCal.M_OverBoostTab",
	},
	"Adaption": {
		"Temp limit for adaption|AdpFuelCal.T_AdaptLim",
		"Fuelcut enabled|FCutCal.ST_Enable",
		"Closed loop regulation|LambdaCal.ST_Enable",
		"Purge enabled|PurgeCal.ST_PurgeEnable",
		"Biopower enabled|E85Cal.ST_Enable",
	},
	"Myrtilos": {
		"Register EU0D",
		"MyrtilosCal.Launch_DisableSpeed",
		"MyrtilosCal.Launch_Ign_fi_Min",
		"MyrtilosCal.Launch_RPM",
		"MyrtilosCal.Launch_InjFac_at_rpm",
		"MyrtilosCal.Launch_PWM_max_at_stand",
		"MyrtilosAdap.WBLambda_FeedbackMap",
		"MyrtilosAdap.WBLambda_FFMap",
	},
}
