package dtc

var T5DTCS = map[string]DTCInfo{
	"Adapt_error":       {"", "Adaption error counter"},
	"Adapt_fel":         {"", "Adaption error counter"},
	"Airpump_error":     {"", "Airpump control error counter"},
	"Cat_error":         {"", "Catalyst error counter"},
	"Cyl_fel":           {"", "Counter for number of faults on camshaftsensor"},
	"Dog_error":         {"", "Watchdog error counter"},
	"Dog_fel":           {"", "Watch dog error counter"},
	"Hast_error":        {"", "Speed signal error counter"},
	"Hast_fel":          {"", "Vehicle speed sensor counter"},
	"Idle_error":        {"", "Idle control error counter"},
	"Idle_fel":          {"", "Idle speed control error counter"},
	"Kam_fel":           {"", "Not used"},
	"Kat_fel":           {"", "Catalythic converter error counter."},
	"Kat_tro_fel":       {"", "Counter for probable catalythic converter errors."},
	"Kyl_error":         {"", "Coolant temperature sensor error counter"},
	"Kyl_fel":           {"", "Water temp sensor error counter"},
	"Luft_error":        {"", "Intake air temperature sensor error counter"},
	"Luft_fel":          {"", "Air temp sensor error counter"},
	"Mis_CVS_error":     {"", "Misfire error counter"},
	"Mis_heating_error": {"", "Misfire catalyst overheating error counter"},
	"Purge_error":       {"", "Purge valve control error counter"},
	"Purge_fel":         {"", "Purge control error counter"},
	"R_sond_error":      {"", "Rear (second) O2 sensor error counter"},
	"RAM_error":         {"", "SRAM integrity error counter"},
	"RAM_fel":           {"", "RAM error counter"},
	"ROM_error":         {"", "Flash (ROM) integrity error counter"},
	"ROM_fel":           {"", "ROM error counter"},
	"Sonc_fel":          {"", "Lambda probe error counter"},
	"Sond_error":        {"", "Front (first) O2 sensor error counter"},
	"Sond_omsl_error":   {"", "Lambda probe control error counter"},
	"Sync_error":        {"", "Sync error counter"},
	"Trott_error":       {"", "Throttle position sensor error counter"},
	"Trott_fel":         {"", "Throttle position sensor error counter"},
	"Tryck_error":       {"", "MAP sensor error counter"},
	"Tryck_fel":         {"", "Pressure sensor error counter"},
	"VSS_error":         {"", "VSS (Vehicle Security System) error counter"},
}
