package symbol

// var axisT7 = AxisInformation{}

var axisT7 = AxisInformation{
	"AdpFuelCal.T_AdaptLim": Axis{
		"",
		"",
		"AdpFuelCal.T_AdaptLim",
		"",
		"",
		"Water temp limit for adaption, Resolution is ",
		"",
		"",
	},
	"AftSt1ExtraCal.EnrFacMap": Axis{
		"AftStCal1.T_EngineSP",
		"AftSt1ExtraCal.p_AirAmbSP",
		"AftSt1ExtraCal.EnrFacMap",
		"Temp °C",
		"Pressure kPa",
		"",
		"",
		"",
	},
	"AftSt2ExtraCal.EnrFacMap": Axis{
		"AftStCal2.T_EngineSP",
		"AftSt2ExtraCal.p_AirAmbSP",
		"AftSt2ExtraCal.EnrFacMap",
		"Temp °C",
		"Pressure kPa",
		"",
		"",
		"",
	},
	"AftSt2ExtraCal.EnrMapE85": Axis{
		"AftSt2ExtraCal.ActualE85SP",
		"AftStCal2.T_EngineSP",
		"AftSt2ExtraCal.EnrMapE85",
		"E85 percentage",
		"Temp °C",
		"",
		"",
		"",
	},
	"AftStCal1.DecrDelayE85Tab": Axis{
		"",
		"AftStCal1.T_EngineSP",
		"AftStCal1.DecrDelayE85Tab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AftStCal1.DecrDelayTab": Axis{
		"",
		"AftStCal1.T_EngineSP",
		"AftStCal1.DecrDelayTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AftStCal1.EnrFacE85Tab": Axis{
		"",
		"AftStCal2.T_EngineSP",
		"AftStCal1.EnrFacE85Tab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AftStCal1.EnrFacTab": Axis{
		"",
		"AftStCal2.T_EngineSP",
		"AftStCal1.EnrFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AftStCal2.DecrDelayTab": Axis{
		"",
		"AftStCal2.T_EngineSP",
		"AftStCal2.DecrDelayTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AftStCal2.EnrFacE85Tab": Axis{
		"",
		"AftStCal2.T_EngineSP",
		"AftStCal2.EnrFacE85Tab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AftStCal2.EnrFacTab": Axis{
		"",
		"AftStCal2.T_EngineSP",
		"AftStCal2.EnrFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AirCompCal.AirLimTab": Axis{
		"",
		"AirCompCal.T_AirLimSP",
		"AirCompCal.AirLimTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AirCompCal.AirTab": Axis{
		"",
		"AirCompCal.T_AirLimSP",
		"AirCompCal.AirTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"AirCompCal.PressMap": Axis{
		"AirCtrlCal.x_axis",
		"AirCtrlCal.y_axis",
		"AirCompCal.PressMap",
		"mg/c",
		"rpm",
		"kPa",
		"",
		"",
	},
	"AirCompCal.PresTab": Axis{
		"",
		"AirCompCal.p_PresSP",
		"AirCompCal.PresTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"AirCtrlCal.m_MaxAirE85Ta": Axis{
		"",
		"AirCtrlCal.y_axis",
		"AirCtrlCal.m_MaxAirE85Ta",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"AirCtrlCal.m_MaxAirPetTa": Axis{
		"",
		"AirCtrlCal.y_axis",
		"AirCtrlCal.m_MaxAirPetTa",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"AirCtrlCal.m_MaxAirTab": Axis{
		"",
		"AirCtrlCal.y_axis",
		"AirCtrlCal.m_MaxAirTab",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"AirCtrlCal.map": Axis{
		"AirCtrlCal.x_axis",
		"AirCtrlCal.y_axis",
		"AirCtrlCal.map",
		"mg/c",
		"rpm",
		"bit",
		"",
		"",
	},
	"AirMinLimCal.p_AirAmbTab": Axis{
		"",
		"AirMinLimCal.v_VehicleSP",
		"AirMinLimCal.p_AirAmbTab",
		"x-axis",
		"km/h",
		"kPa",
		"",
		"",
	},
	"AirMinLimCal.Q_DashPotMap": Axis{
		"AirMinLimCal.m_AirXSP",
		"AirMinLimCal.n_EngYSP",
		"AirMinLimCal.Q_DashPotMap",
		"mg/c",
		"rpm",
		"g/s",
		"",
		"",
	},
	"AirMinLimCal.Q_MinLoadTab": Axis{
		"",
		"AirMinLimCal.v_VehicleSP",
		"AirMinLimCal.Q_MinLoadTab",
		"x-axis",
		"km/h",
		"g/s",
		"",
		"",
	},
	"AirMinLimCal.v_VehicleTab": Axis{
		"",
		"AirMinLimCal.v_VehicleSP",
		"AirMinLimCal.v_VehicleTab",
		"x-axis",
		"km/h",
		"km/h",
		"",
		"",
	},
	"AreaCal.Q_VenturiTab": Axis{
		"",
		"AreaCal.Q_VenturiSP",
		"AreaCal.Q_VenturiTab",
		"x-axis",
		"g/s",
		"g/s",
		"",
		"",
	},
	"AreaCal.Table": Axis{
		"",
		"AreaCal.Area",
		"AreaCal.Table",
		"x-axis",
		"mm^2",
		"z-axis",
		"",
		"",
	},
	"BFuelAdap.V_FuelConsMap": Axis{
		"FuelConsCal.m_AirInlXSP",
		"FuelConsCal.n_EngineYSP",
		"BFuelAdap.V_FuelConsMap",
		"mg/c",
		"rpm",
		"ml",
		"",
		"",
	},
	"BFuelCal.E85Map": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"BFuelCal.E85Map",
		"mg/c",
		"rpm",
		"Fuel correction factor",
		"",
		"",
	},
	"BFuelCal.GasMap": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"BFuelCal.GasMap",
		"mg/c",
		"rpm",
		"Fuel correction factor",
		"",
		"",
	},
	"BFuelCal.Map": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"BFuelCal.Map",
		"mg/c",
		"rpm",
		"Fuel correction factor",
		"",
		"",
	},
	"BFuelCal.StartMap": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"BFuelCal.StartMap",
		"mg/c",
		"rpm",
		"Fuel correction factor",
		"",
		"",
	},
	"BFuelCal.WWCompAlphaTab": Axis{
		"",
		"BFuelCal.T_WWCompSP",
		"BFuelCal.WWCompAlphaTab",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"BFuelCal.WWCompRampTab": Axis{
		"",
		"BFuelCal.T_WWCompSP",
		"BFuelCal.WWCompRampTab",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"BFuelCal.WWPressCompBetaTab": Axis{
		"",
		"BFuelCal.p_WWPressCompSP",
		"BFuelCal.WWPressCompBetaTab",
		"x-axis",
		"",
		"z-axis",
		"",
		"",
	},
	"BFuelCal.WWTempCompBetaTab": Axis{
		"",
		"BFuelCal.T_WWCompSP",
		"BFuelCal.WWTempCompBetaTab",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"BFuelCal2.Map": Axis{
		"BFuelCal2.AirXSP",
		"BFuelCal2.RpmYSP",
		"BFuelCal2.Map",
		"mg/c",
		"rpm",
		"Fuel correction factor",
		"",
		"",
	},
	"BFuelCal2.StartMap": Axis{
		"BFuelCal2.AirXSP",
		"BFuelCal2.RpmYSP",
		"BFuelCal2.StartMap",
		"mg/c",
		"rpm",
		"Fuel correction factor",
		"",
		"",
	},
	"BlockHeatCal.AftSt2FacTab": Axis{
		"",
		"BlockHeatCal.T_AirInletSP",
		"BlockHeatCal.AftSt2FacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"BlockHeatCal.C_PartNFacTab": Axis{
		"",
		"BlockHeatCal.T_AirInletSP",
		"BlockHeatCal.C_PartNFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"BlockHeatCal.Q_StartFacTab": Axis{
		"",
		"BlockHeatCal.T_AirInletSP",
		"BlockHeatCal.Q_StartFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"BoostCal.AntiHowlPresTab": Axis{
		"",
		"BoostCal.AntiHowlPairSP",
		"BoostCal.AntiHowlPresTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"BoostCal.DMap": Axis{
		"BoostCal.PIDXSP",
		"BoostCal.PIDYSP",
		"BoostCal.DMap",
		"mg/c error",
		"rpm",
		"D factor",
		"AirDIFF",
		"ActualIn.n_Engine",
	},
	"BoostCal.HighAltMap": Axis{
		"BoostCal.SetLoad2XSP",
		"BoostCal.HighAltTabSP",
		"BoostCal.HighAltMap",
		"mg/c",
		"kPa",
		"%",
		"",
		"",
	},
	"BoostCal.I_LimTab": Axis{
		"",
		"BoostCal.n_EngSP",
		"BoostCal.I_LimTab",
		"x-axis",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"BoostCal.IMap": Axis{
		"BoostCal.PIDXSP",
		"BoostCal.PIDYSP",
		"BoostCal.IMap",
		"mg/c error",
		"rpm",
		"I factor",
		"AirDIFF",
		"ActualIn.n_Engine",
	},
	"BoostCal.p_DiffILimMap": Axis{
		"BoostCal.p_DiffILimXSP",
		"BoostCal.p_DiffILimYSP",
		"BoostCal.p_DiffILimMap",
		"kPa",
		"mg/c",
		"z-axis",
		"",
		"",
	},
	"BoostCal.P_LimTab": Axis{
		"",
		"BoostCal.n_EngSP",
		"BoostCal.P_LimTab",
		"x-axis",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"BoostCal.PercAdapTab": Axis{
		"",
		"BoostCal.m_AirAdapSP",
		"BoostCal.PercAdapTab",
		"x-axis",
		"mg/c",
		"%",
		"",
		"",
	},
	"BoostCal.PMap": Axis{
		"BoostCal.PIDXSP",
		"BoostCal.PIDYSP",
		"BoostCal.PMap",
		"mg/c error",
		"rpm",
		"P factor",
		"AirDIFF",
		"ActualIn.n_Engine",
	},
	"BoostCal.pwm_E85adjTab": Axis{
		"",
		"BoostCal.PIDYSP",
		"BoostCal.pwm_E85adjTab",
		"x-axis",
		"",
		"z-axis",
		"",
		"",
	},
	"BoostCal.PWMTempTab": Axis{
		"",
		"BoostCal.PWMTempSP",
		"BoostCal.PWMTempTab",
		"x-axis",
		"°C",
		"%",
		"",
		"",
	},
	"BoostCal.RegMap": Axis{
		"BoostCal.SetLoadXSP",
		"BoostCal.n_EngSP",
		"BoostCal.RegMap",
		"mg/c",
		"rpm",
		"% PWM",
		"m_Request",
		"ActualIn.n_Engine",
	},
	"BstKnkCal.MaxAirmass": Axis{
		"BstKnkCal.OffsetXSP",
		"BstKnkCal.n_EngYSP",
		"BstKnkCal.MaxAirmass",
		"° ignition retard (Ioff)",
		"rpm",
		"mg/c",
		"IgnProt.fi_Offset",
		"ActualIn.n_Engine",
	},
	"BstKnkCal.MaxAirmassAu": Axis{
		"BstKnkCal.OffsetXSP",
		"BstKnkCal.n_EngYSP",
		"BstKnkCal.MaxAirmassAu",
		"° ignition retard (Ioff)",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"CatDiagCal.HiMapOx1CycleTime": Axis{
		"CatDiagCal.LoadTab",
		"CatDiagCal.RpmTab",
		"CatDiagCal.HiMapOx1CycleTime",
		"x-axis",
		"y-axis",
		"ms",
		"",
		"",
	},
	"CatDiagCal.LoMapOx1CycleTime": Axis{
		"CatDiagCal.LoadTab",
		"CatDiagCal.RpmTab",
		"CatDiagCal.LoMapOx1CycleTime",
		"x-axis",
		"y-axis",
		"ms",
		"",
		"",
	},
	"CatDiagCal.Ox2DevMaxMap": Axis{
		"CatDiagCal.LoadTab",
		"CatDiagCal.RpmTab",
		"CatDiagCal.Ox2DevMaxMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"CatDiagLevCal.ErrorLim": Axis{
		"CatDiagLevCal.m_SP",
		"CatDiagLevCal.T_CatSP",
		"CatDiagLevCal.ErrorLim",
		"mg/c",
		"C",
		"ms",
		"",
		"",
	},
	"CatModCal.n_CombStart": Axis{
		"",
		"CatModCal.T_SPCombStart",
		"CatModCal.n_CombStart",
		"x-axis",
		"C",
		"z-axis",
		"",
		"",
	},
	"CatModCal.T_Offset": Axis{
		"",
		"CatModCal.T_SPCombStart",
		"CatModCal.T_Offset",
		"x-axis",
		"C",
		"C",
		"",
		"",
	},
	"CatModCal.T_SteadyState": Axis{
		"CatModCal.m_SP",
		"CatModCal.n_SP",
		"CatModCal.T_SteadyState",
		"mg/c",
		"rpm",
		"C",
		"",
		"",
	},
	"CruiseCal.a_AccRequest": Axis{
		"",
		"CruiseComCal.v_Delta",
		"CruiseCal.a_AccRequest",
		"x-axis",
		"km/h",
		"m/s^2",
		"",
		"",
	},
	"CruiseCal.a_DecReqMap": Axis{
		"CruiseCal.v_DiffXSP",
		"CruiseCal.v_ActualYSP",
		"CruiseCal.a_DecReqMap",
		"km/h",
		"km/h",
		"m/s^2",
		"",
		"",
	},
	"CruiseCal.a_DecRequest": Axis{
		"",
		"CruiseComCal.v_Delta",
		"CruiseCal.a_DecRequest",
		"x-axis",
		"km/h",
		"m/s^2",
		"",
		"",
	},
	"CruiseCal.M_GradientNeg": Axis{
		"",
		"CruiseCal.M_GradActual",
		"CruiseCal.M_GradientNeg",
		"x-axis",
		"Nm",
		"Nm",
		"",
		"",
	},
	"CruiseCal.M_GradientPos": Axis{
		"",
		"CruiseCal.M_GradActual",
		"CruiseCal.M_GradientPos",
		"x-axis",
		"Nm",
		"Nm",
		"",
		"",
	},
	"CruiseCal.v_LimitNeg": Axis{
		"",
		"CruiseCal.v_RequestNormal",
		"CruiseCal.v_LimitNeg",
		"x-axis",
		"km/h",
		"km/h",
		"",
		"",
	},
	"CruiseCal.v_LimitNormal": Axis{
		"",
		"CruiseCal.v_RequestNormal",
		"CruiseCal.v_LimitNormal",
		"x-axis",
		"km/h",
		"km/h",
		"",
		"",
	},
	"CruiseCal.v_LimitPos": Axis{
		"",
		"CruiseCal.v_RequestNormal",
		"CruiseCal.v_LimitPos",
		"x-axis",
		"km/h",
		"km/h",
		"",
		"",
	},
	"CruiseComCal.M_Offset": Axis{
		"",
		"CruiseComCal.v_Delta",
		"CruiseComCal.M_Offset",
		"x-axis",
		"km/h",
		"%",
		"",
		"",
	},
	"CruiseComCal.M_RoadTorque": Axis{
		"",
		"CruiseComCal.v_Actual",
		"CruiseComCal.M_RoadTorque",
		"x-axis",
		"km/h",
		"Nm",
		"",
		"",
	},
	"DiffPSCal.M_LimitTab": Axis{
		"",
		"DiffPSCal.v_DiffSP",
		"DiffPSCal.M_LimitTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"DiffPSCal.t_LimDelayTab": Axis{
		"",
		"DiffPSCal.M_EngineSP",
		"DiffPSCal.t_LimDelayTab",
		"x-axis",
		"Nm",
		"ms",
		"",
		"",
	},
	"DisplAdap.LamScannerTab1": Axis{
		"",
		"DisplAdap.AD_ScannerSP",
		"DisplAdap.LamScannerTab1",
		"x-axis",
		"AD",
		"Lam",
		"",
		"",
	},
	"DisplAdap.LamScannerTab2": Axis{
		"",
		"DisplAdap.AD_ScannerSP",
		"DisplAdap.LamScannerTab2",
		"x-axis",
		"AD",
		"Lam",
		"",
		"",
	},
	"DisplAdap.LamScannerTab3": Axis{
		"",
		"DisplAdap.AD_ScannerSP",
		"DisplAdap.LamScannerTab3",
		"x-axis",
		"AD",
		"Lam",
		"",
		"",
	},
	"DisplAdap.LamScannerTab4": Axis{
		"",
		"DisplAdap.AD_ScannerSP",
		"DisplAdap.LamScannerTab4",
		"x-axis",
		"AD",
		"Lam",
		"",
		"",
	},
	"E85Cal.X_EthanolActEnrFacMap": Axis{
		"E85Cal.X_EthanolActualXSP",
		"E85Cal.T_EngTempYSP",
		"E85Cal.X_EthanolActEnrFacMap",
		"E85 percentage",
		"Temp °C",
		"",
		"",
		"",
	},
	"E85CldStCal.EnrMap": Axis{
		"E85CldStCal.T_EngineSP",
		"E85CldStCal.n_CombustionTab",
		"E85CldStCal.EnrMap",
		"Temp °C",
		"Number of combustions",
		"",
		"",
		"",
	},
	"E85FSCal.V_IncStaLimTab": Axis{
		"",
		"E85FSCal.V_IncStableSP",
		"E85FSCal.V_IncStaLimTab",
		"x-axis",
		"DL",
		"Volume DL",
		"",
		"",
	},
	"E85FSCal.V_IncTrigLim": Axis{
		"",
		"E85FSCal.V_IncTrigSP",
		"E85FSCal.V_IncTrigLim",
		"x-axis",
		"DL",
		"Volume DL",
		"",
		"",
	},
	"EmLimCal.m_AutMaxIncrMap": Axis{
		"EmLimCal.AutGearXSP",
		"EmLimCal.n_EngYSP",
		"EmLimCal.m_AutMaxIncrMap",
		"x-axis",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"EmLimCal.m_MaxIncrMap": Axis{
		"EmLimCal.GearXSP",
		"EmLimCal.n_EngYSP",
		"EmLimCal.m_MaxIncrMap",
		"ascii",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"EmLimCal.RampFactorMap": Axis{
		"EmLimCal.PedDeltaXSP",
		"EmLimCal.X_PedYSP",
		"EmLimCal.RampFactorMap",
		"x-axis",
		"%",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut1BMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut1BMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut1OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut1OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut2BMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut2BMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut2OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut2OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut3Map": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut3Map",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut3OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut3OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut4Map": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut4Map",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut4OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut4OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut5Map": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut5Map",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInAut5OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipInAut5OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInMan1Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipInMan1Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInMan2Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipInMan2Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInMan3Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipInMan3Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInMan4Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipInMan4Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipInMan5Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipInMan5Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut1OM": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut1OM",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut1OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut1OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut2OM": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut2OM",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut2OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut2OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut3Map": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut3Map",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut3OM": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut3OM",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut3OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut3OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut4Map": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut4Map",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut4OM": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut4OM",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut4OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut4OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut5Map": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut5Map",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut5OM": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut5OM",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutAut5OMap": Axis{
		"EngTipCal.n_EngDiffXSP",
		"EngTipCal.n_GearBoxYSP",
		"EngTipCal.m_TipOutAut5OMap",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutMan1Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipOutMan1Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutMan2Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipOutMan2Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutMan3Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipOutMan3Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutMan4Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipOutMan4Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.m_TipOutMan5Map": Axis{
		"EngTipCal.m_TipXSP",
		"EngTipCal.n_EngineYSP",
		"EngTipCal.m_TipOutMan5Map",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA1OTab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA1OTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA2OTab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA2OTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA3OTab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA3OTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA3Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA3Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA4OTab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA4OTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA4Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA4Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA5OTab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA5OTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFA5Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFA5Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFM1Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFM1Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFM2Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFM2Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFM3Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFM3Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFM4Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFM4Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EngTipCal.X_TipInRFM5Tab": Axis{
		"",
		"EngTipCal.X_IndAccXSP",
		"EngTipCal.X_TipInRFM5Tab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EvapDiagCal.CalcFac": Axis{
		"",
		"EvapDiagCal.RampSumTab",
		"EvapDiagCal.CalcFac",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"EvapDiagCal.LeakFacTest1MAT": Axis{
		"EvapDiagCal.Test1Ramp2ResSP",
		"EvapDiagCal.V_Test1FuelSP",
		"EvapDiagCal.LeakFacTest1MAT",
		"",
		"Volume (milliLiter)",
		"mg/c",
		"",
		"",
	},
	"EvapDiagCal.LeakFacTest2MAT": Axis{
		"EvapDiagCal.Test2Ramp2ResSP",
		"EvapDiagCal.V_Test2FuelSP",
		"EvapDiagCal.LeakFacTest2MAT",
		"",
		"Volume (milliLiter)",
		"mg/c",
		"",
		"",
	},
	"ExhaustCal.fi_IgnMap": Axis{
		"ExhaustCal.m_AirSP",
		"ExhaustCal.fi_IgnSP",
		"ExhaustCal.fi_IgnMap",
		"x-axis",
		"°",
		"°C",
		"",
		"",
	},
	"ExhaustCal.m_AirTau1Tab": Axis{
		"",
		"ExhaustCal.m_AirSP",
		"ExhaustCal.m_AirTau1Tab",
		"x-axis",
		"°C",
		"s",
		"",
		"",
	},
	"ExhaustCal.m_AirTau2Tab": Axis{
		"",
		"ExhaustCal.m_AirSP",
		"ExhaustCal.m_AirTau2Tab",
		"x-axis",
		"°C",
		"s",
		"",
		"",
	},
	"ExhaustCal.T_ExhaustTab": Axis{
		"",
		"ExhaustCal.T_ExhaustSP",
		"ExhaustCal.T_ExhaustTab",
		"x-axis",
		"°C",
		"°C",
		"",
		"",
	},
	"ExhaustCal.T_Lambda1Map": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"ExhaustCal.T_Lambda1Map",
		"mg/c",
		"rpm",
		"°C",
		"",
		"",
	},
	"ExhaustCal.T_LimitTab": Axis{
		"",
		"ExhaustCal.T_LimitSP",
		"ExhaustCal.T_LimitTab",
		"x-axis",
		"°C",
		"°C",
		"",
		"",
	},
	"F_KnkDetAdap.FKnkCntMap": Axis{
		"KnkDetCal.m_AirXSP",
		"KnkDetCal.n_EngYSP",
		"F_KnkDetAdap.FKnkCntMap",
		"mg/c",
		"rpm",
		"# knocks",
		"",
		"",
	},
	"F_KnkDetAdap.RKnkCntMap": Axis{
		"KnkDetCal.m_AirXSP",
		"KnkDetCal.n_EngYSP",
		"F_KnkDetAdap.RKnkCntMap",
		"mg/c",
		"rpm",
		"# knocks",
		"",
		"",
	},
	"FCutCal.FuelFactor": Axis{
		"",
		"FCutCal.n_CombSP",
		"FCutCal.FuelFactor",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"FuelConsCal.Tab": Axis{
		"",
		"FuelConsCal.AirSP",
		"FuelConsCal.Tab",
		"x-axis",
		"mg/c",
		"z-axis",
		"",
		"",
	},
	"HotStCal1.DecrDelayTab": Axis{
		"",
		"HotStCal1.T_EngineSP",
		"HotStCal1.DecrDelayTab",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"HotStCal1.EnrFacE85Tab": Axis{
		"",
		"HotStCal1.T_EngineSP",
		"HotStCal1.EnrFacE85Tab",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"HotStCal1.EnrFacTab": Axis{
		"",
		"HotStCal1.T_EngineSP",
		"HotStCal1.EnrFacTab",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"HotStCal2.RestartFacTab": Axis{
		"",
		"HotStCal2.t_RestartSP",
		"HotStCal2.RestartFacTab",
		"x-axis",
		"sec",
		"z-axis",
		"",
		"",
	},
	"HotStCal2.RestartMap": Axis{
		"HotStCal2.t_RestartYSP",
		"HotStCal2.RestartE85XSP",
		"HotStCal2.RestartMap",
		"Time/Seconds",
		"SoakTime",
		"EnrFactor",
		"",
		"",
	},
	"IdleCal.C_PartDrive": Axis{
		"",
		"IdleCal.T_EngineSP",
		"IdleCal.C_PartDrive",
		"x-axis",
		"°C",
		"g/s",
		"",
		"",
	},
	"IdleCal.C_PartNeutral": Axis{
		"",
		"IdleCal.T_EngSP",
		"IdleCal.C_PartNeutral",
		"x-axis",
		"°C",
		"g/s",
		"",
		"",
	},
	"IdleCal.DelayDriveAct": Axis{
		"",
		"IdleCal.T_EngineSP",
		"IdleCal.DelayDriveAct",
		"x-axis",
		"°C",
		"ms",
		"",
		"",
	},
	"IdleCal.DelayDriveRel": Axis{
		"",
		"IdleCal.T_EngineSP",
		"IdleCal.DelayDriveRel",
		"x-axis",
		"°C",
		"ms",
		"",
		"",
	},
	"IdleCal.I_PartTab": Axis{
		"",
		"IdleCal.P_PartSP",
		"IdleCal.I_PartTab",
		"x-axis",
		"rpm",
		"g/s",
		"",
		"",
	},
	"IdleCal.LOffTab": Axis{
		"",
		"IdleCal.LOffSP",
		"IdleCal.LOffTab",
		"x-axis",
		"°",
		"g/s",
		"",
		"",
	},
	"IdleCal.n_DeltaTAB": Axis{
		"",
		"IdleCal.n_DeltaSP",
		"IdleCal.n_DeltaTAB",
		"x-axis",
		"",
		"z-axis",
		"",
		"",
	},
	"IdleCal.n_EngLOffDrive": Axis{
		"",
		"IdleCal.n_EngLOffSP",
		"IdleCal.n_EngLOffDrive",
		"x-axis",
		"rpm",
		"rpm",
		"",
		"",
	},
	"IdleCal.n_EngLOffNeutral": Axis{
		"",
		"IdleCal.n_EngLOffSP",
		"IdleCal.n_EngLOffNeutral",
		"x-axis",
		"rpm",
		"rpm",
		"",
		"",
	},
	"IdleCal.n_EngNomDrive": Axis{
		"",
		"IdleCal.T_EngineSP",
		"IdleCal.n_EngNomDrive",
		"x-axis",
		"°C",
		"rpm",
		"",
		"",
	},
	"IdleCal.n_EngNomNeutral": Axis{
		"",
		"IdleCal.T_EngineSP",
		"IdleCal.n_EngNomNeutral",
		"x-axis",
		"°C",
		"rpm",
		"",
		"",
	},
	"IdleCal.NeutralAirPartTAB": Axis{
		"",
		"EvapDiagCal.RampSumTab",
		"IdleCal.NeutralAirPartTAB",
		"x-axis",
		"y-axis",
		"%",
		"",
		"",
	},
	"IdleCal.P_PartTab": Axis{
		"",
		"IdleCal.P_PartSP",
		"IdleCal.P_PartTab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"IdleCal.Q_AirAmbTab": Axis{
		"",
		"IdleCal.p_AirAmbSP",
		"IdleCal.Q_AirAmbTab",
		"x-axis",
		"kPa",
		"g/s",
		"",
		"",
	},
	"IdleCal.Q_AltStartTAB": Axis{
		"",
		"IdleCal.p_AltStartSP",
		"IdleCal.Q_AltStartTAB",
		"x-axis",
		"kPa",
		"g/s",
		"",
		"",
	},
	"IdleCal.Q_IdleOffsMAP": Axis{
		"IdleCal.T_EngRPMOffSP",
		"IdleCal.n_RPMOffYSP",
		"IdleCal.Q_IdleOffsMAP",
		"°C",
		"rpm",
		"g/s",
		"",
		"",
	},
	"IdleCal.Q_LOffRpmDrive": Axis{
		"",
		"IdleCal.n_EngLOffSP",
		"IdleCal.Q_LOffRpmDrive",
		"x-axis",
		"rpm",
		"g/s",
		"",
		"",
	},
	"IdleCal.Q_LOffRpmNeutral": Axis{
		"",
		"IdleCal.n_EngLOffSP",
		"IdleCal.Q_LOffRpmNeutral",
		"x-axis",
		"rpm",
		"g/s",
		"",
		"",
	},
	"IdleCal.Q_StartOffsTab": Axis{
		"",
		"IdleCal.p_AltStartSP",
		"IdleCal.Q_StartOffsTab",
		"x-axis",
		"kPa",
		"g/s",
		"",
		"",
	},
	"IdleCal.StartRedFacMat": Axis{
		"IdleCal.n_EngDiffSP",
		"IdleCal.t_yaxis",
		"IdleCal.StartRedFacMat",
		"rpm",
		"°C",
		"z-axis",
		"",
		"",
	},
	"IdleCal.T_AirTab": Axis{
		"",
		"IdleCal.p_AirAmbSP",
		"IdleCal.T_AirTab",
		"x-axis",
		"kPa",
		"g/s",
		"",
		"",
	},
	"IdleCal.X_FirstDrvE85FuelTAB": Axis{
		"",
		"IdleCal.T_EngFirstDrvSP",
		"IdleCal.X_FirstDrvE85FuelTAB",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"IdleCal.X_FirstDrvFuelTAB": Axis{
		"",
		"IdleCal.T_EngFirstDrvSP",
		"IdleCal.X_FirstDrvFuelTAB",
		"x-axis",
		"Temp °C",
		"z-axis",
		"",
		"",
	},
	"IdleCal.X_mLOffHighAltTab": Axis{
		"",
		"IdleCal.n_RpmDiffLOffSP",
		"IdleCal.X_mLOffHighAltTab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"IgnCal.MinMap": Axis{
		"IgnCal.m_AirXSP",
		"IgnCal.n_EngYSP",
		"IgnCal.MinMap",
		"mg/c",
		"rpm",
		"°",
		"",
		"",
	},
	"IgnE85Cal.fi_AbsMap": Axis{
		"IgnNormCal.m_AirXSP",
		"IgnNormCal.n_EngYSP",
		"IgnE85Cal.fi_AbsMap",
		"mg/c",
		"rpm",
		"° BDTC",
		"",
		"",
	},
	"IgnIdleCal.fi_IdleMap": Axis{
		"IgnIdleCal.m_AirXSP",
		"IgnIdleCal.n_EngYSP",
		"IgnIdleCal.fi_IdleMap",
		"mg/c",
		"rpm",
		"° BDTC",
		"",
		"",
	},
	"IgnIdleCal.fi_MinTab": Axis{
		"",
		"IgnIdleCal.n_EngMinSP",
		"IgnIdleCal.fi_MinTab",
		"x-axis",
		"rpm",
		"°",
		"",
		"",
	},
	"IgnIdleCal.Tab": Axis{
		"",
		"IgnIdleCal.n_EngDiffSP",
		"IgnIdleCal.Tab",
		"x-axis",
		"rpm",
		"° BDTC",
		"",
		"",
	},
	"IgnJerkCal.fi_Tab": Axis{
		"",
		"IgnJerkCal.n_DiffXSP",
		"IgnJerkCal.fi_Tab",
		"x-axis",
		"rpm",
		"°",
		"",
		"",
	},
	"IgnJerkCal.n_LimTab": Axis{
		"",
		"IgnJerkCal.n_LimTabSP",
		"IgnJerkCal.n_LimTab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"IgnKnkCal.AdpHighLimTab": Axis{
		"",
		"IgnKnkCal.n_EngYSP",
		"IgnKnkCal.AdpHighLimTab",
		"x-axis",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"IgnKnkCal.AdpLowLimTab": Axis{
		"",
		"IgnKnkCal.n_EngYSP",
		"IgnKnkCal.AdpLowLimTab",
		"x-axis",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"IgnKnkCal.fi_Map1MaxOffset": Axis{
		"",
		"IgnKnkCal.n_EngYSP",
		"IgnKnkCal.fi_Map1MaxOffset",
		"x-axis",
		"rpm",
		"°",
		"",
		"",
	},
	"IgnKnkCal.fi_Offset": Axis{
		"",
		"IgnKnkCal.n_EngYSP",
		"IgnKnkCal.fi_Offset",
		"x-axis",
		"rpm",
		"°",
		"",
		"",
	},
	"IgnKnkCal.IndexMap": Axis{
		"IgnKnkCal.m_AirXSP",
		"IgnKnkCal.n_EngYSP",
		"IgnKnkCal.IndexMap",
		"mg/c",
		"rpm",
		"° pull",
		"",
		"",
	},
	"IgnLOffCal.CombTab": Axis{
		"",
		"IgnLOffCal.T_AirInletSP",
		"IgnLOffCal.CombTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"IgnLOffCal.fi_MapOffset": Axis{
		"IgnLOffCal.m_AirXSP",
		"IgnLOffCal.n_EngYSP",
		"IgnLOffCal.fi_MapOffset",
		"mg/c",
		"rpm",
		"°",
		"",
		"",
	},
	"IgnLOffCal.N_AirTab": Axis{
		"",
		"IgnLOffCal.T_AirInletSP",
		"IgnLOffCal.N_AirTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"IgnLOffCal.n_CombAftSt": Axis{
		"",
		"IgnLOffCal.T_CombAftStSP",
		"IgnLOffCal.n_CombAftSt",
		"x-axis",
		"temp °C /10",
		"combustions",
		"",
		"",
	},
	"IgnNormCal.GasMap": Axis{
		"IgnNormCal.m_AirXSP",
		"IgnNormCal.n_EngYSP",
		"IgnNormCal.GasMap",
		"mg/c",
		"rpm",
		"° BDTC",
		"",
		"",
	},
	"IgnNormCal.Map": Axis{
		"IgnNormCal.m_AirXSP",
		"IgnNormCal.n_EngYSP",
		"IgnNormCal.Map",
		"mg/c",
		"rpm",
		"° BDTC",
		"",
		"",
	},
	"IgnNormCal2.Map": Axis{
		"IgnNormCal.m_AirXSP",
		"IgnNormCal.n_EngYSP",
		"IgnNormCal2.Map",
		"mg/c",
		"rpm",
		"° BDTC",
		"",
		"",
	},
	"IgnOffsCal.DNCompFast": Axis{
		"IgnOffsCal.Q_ExtraSP",
		"IdleCal.T_EngineSP",
		"IgnOffsCal.DNCompFast",
		"x-axis",
		"C",
		"z-axis",
		"",
		"",
	},
	"IgnOffsCal.DNCompSlow": Axis{
		"IgnOffsCal.Q_ExtraSP",
		"IdleCal.T_EngineSP",
		"IgnOffsCal.DNCompSlow",
		"x-axis",
		"C",
		"z-axis",
		"",
		"",
	},
	"IgnStartCal.fi_StartMap": Axis{
		"IgnStartCal.X_EthActSP",
		"IgnStartCal.T_AirSP",
		"IgnStartCal.fi_StartMap",
		"rpm",
		"°C",
		"°",
		"ActualIn.n_Engine",
		"ActualIn.T_AirInlet",
	},
	"IgnTempCal.AirMap": Axis{
		"IgnTempCal.n_EngXSP",
		"IgnTempCal.T_AirYSP",
		"IgnTempCal.AirMap",
		"rpm",
		"°C",
		"°",
		"",
		"",
	},
	"IgnTempCal.EngMap": Axis{
		"IgnTempCal.n_EngXSP",
		"IgnTempCal.T_EngYSP",
		"IgnTempCal.EngMap",
		"rpm",
		"°C",
		"°",
		"",
		"",
	},
	"InjAnglCal.Map": Axis{
		"InjAnglCal.AirXSP",
		"InjAnglCal.RpmYSP",
		"InjAnglCal.Map",
		"mg/c",
		"Rpm",
		"°",
		"",
		"",
	},
	"InjCorrCal.BattCorrTab": Axis{
		"",
		"InjCorrCal.BattCorrSP",
		"InjCorrCal.BattCorrTab",
		"x-axis",
		"V",
		"z-axis",
		"",
		"",
	},
	"JerkCal.n_EngineTab": Axis{
		"",
		"JerkCal.n_EngineSP",
		"JerkCal.n_EngineTab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"JerkCal.p_AirAmbientTab": Axis{
		"",
		"JerkCal.p_AirAmbientSP",
		"JerkCal.p_AirAmbientTab",
		"x-axis",
		"kPa",
		"kPa",
		"",
		"",
	},
	"JerkCal.T_AirInletTab": Axis{
		"",
		"JerkCal.T_AirInletSP",
		"JerkCal.T_AirInletTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"KnkAdaptCal.ConstantTab": Axis{
		"",
		"KnkAdaptCal.fi_OffsetSP",
		"KnkAdaptCal.ConstantTab",
		"x-axis",
		"°",
		"z-axis",
		"",
		"",
	},
	"KnkAdaptCal.MaxRef": Axis{
		"",
		"KnkAdaptCal.fi_OffsetSP",
		"KnkAdaptCal.MaxRef",
		"x-axis",
		"°",
		"z-axis",
		"",
		"",
	},
	"KnkAdaptCal.WeightMap1": Axis{
		"KnkAdaptCal.m_AirXSP1",
		"KnkAdaptCal.n_EngYSP1",
		"KnkAdaptCal.WeightMap1",
		"mg/c",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"KnkAdaptCal.WeightMap2": Axis{
		"KnkAdaptCal.m_AirXSP2",
		"KnkAdaptCal.n_EngYSP2",
		"KnkAdaptCal.WeightMap2",
		"mg/c",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"KnkDetAdap.KnkCntMap": Axis{
		"KnkDetCal.m_AirXSP",
		"KnkDetCal.n_EngYSP",
		"KnkDetAdap.KnkCntMap",
		"mg/c",
		"rpm",
		"# knocks",
		"",
		"",
	},
	"KnkDetCal.KnockWinOffs": Axis{
		"KnkDetCal.m_AirXSP",
		"KnkDetCal.n_EngYSP",
		"KnkDetCal.KnockWinOffs",
		"mg/c",
		"rpm",
		"°",
		"",
		"",
	},
	"KnkDetCal.RefFactorMap": Axis{
		"KnkDetCal.m_AirXSP",
		"KnkDetCal.n_EngYSP",
		"KnkDetCal.RefFactorMap",
		"mg/c",
		"rpm",
		"Knock sensitivity",
		"",
		"",
	},
	"KnkDetCal.T_EngKnkCntrl": Axis{
		"",
		"KnkDetCal.T_InletAirXSP",
		"KnkDetCal.T_EngKnkCntrl",
		"x-axis",
		"°",
		"°",
		"",
		"",
	},
	"KnkDetCal.X_AverageTab": Axis{
		"",
		"KnkAdaptCal.fi_OffsetSP",
		"KnkDetCal.X_AverageTab",
		"x-axis",
		"°",
		"z-axis",
		"",
		"",
	},
	"KnkFuelCal.EnrichmentMap": Axis{
		"IgnKnkCal.m_AirXSP",
		"IgnKnkCal.n_EngYSP",
		"KnkFuelCal.EnrichmentMap",
		"mg/c",
		"rpm",
		"Enrichment factor",
		"",
		"",
	},
	"KnkFuelCal.fi_MapMaxOff": Axis{
		"KnkFuelCal.m_AirXSP",
		"BstKnkCal.n_EngYSP",
		"KnkFuelCal.fi_MapMaxOff",
		"mg/c",
		"rpm",
		"°",
		"",
		"",
	},
	"KnkFuelCal.fi_MapMaxOffset": Axis{
		"IgnKnkCal.m_AirXSP",
		"IgnKnkCal.n_EngYSP",
		"KnkFuelCal.fi_MapMaxOffset",
		"mg/c",
		"rpm",
		"°",
		"",
		"",
	},
	"KnkFuelCal.WeightTab": Axis{
		"KnkFuelCal.WeightXSP",
		"KnkFuelCal.WeightYSP",
		"KnkFuelCal.WeightTab",
		"rpm",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"KnkSoundRedCal.fi_OffsMap": Axis{
		"IgnNormCal.m_AirXSP",
		"IgnNormCal.n_EngYSP",
		"KnkSoundRedCal.fi_OffsMap",
		"mg/c",
		"rpm",
		"°",
		"",
		"",
	},
	"LambdaCal.CombNrTab2": Axis{
		"",
		"LambdaCal.TempSp",
		"LambdaCal.CombNrTab2",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"LambdaCal.DecCombMap": Axis{
		"LambdaCal.XSp",
		"LambdaCal.YSp",
		"LambdaCal.DecCombMap",
		"mg/c",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"LambdaCal.DecRampMap": Axis{
		"LambdaCal.XSp",
		"LambdaCal.YSp",
		"LambdaCal.DecRampMap",
		"mg/c",
		"y-axis",
		"%",
		"",
		"",
	},
	"LambdaCal.DecStepMap": Axis{
		"LambdaCal.XSp",
		"LambdaCal.YSp",
		"LambdaCal.DecStepMap",
		"mg/c",
		"y-axis",
		"%",
		"",
		"",
	},
	"LambdaCal.HeatLoadLimTab": Axis{
		"",
		"LambdaCal.HeatRpmSP",
		"LambdaCal.HeatLoadLimTab",
		"x-axis",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"LambdaCal.IncCombMap": Axis{
		"LambdaCal.XSp",
		"LambdaCal.YSp",
		"LambdaCal.IncCombMap",
		"mg/c",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"LambdaCal.IncRampMap": Axis{
		"LambdaCal.XSp",
		"LambdaCal.YSp",
		"LambdaCal.IncRampMap",
		"mg/c",
		"y-axis",
		"%",
		"",
		"",
	},
	"LambdaCal.IncStepMap": Axis{
		"LambdaCal.XSp",
		"LambdaCal.YSp",
		"LambdaCal.IncStepMap",
		"mg/c",
		"y-axis",
		"%",
		"",
		"",
	},
	"LambdaCal.LeanStep": Axis{
		"",
		"LambdaCal.U_AdjStepSP",
		"LambdaCal.LeanStep",
		"x-axis",
		"mV",
		"%",
		"",
		"",
	},
	"LambdaCal.MaxLoadE85Tab": Axis{
		"",
		"LambdaCal.RpmSp",
		"LambdaCal.MaxLoadE85Tab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"LambdaCal.MaxLoadNormTab": Axis{
		"",
		"LambdaCal.RpmSp",
		"LambdaCal.MaxLoadNormTab",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"LambdaCal.MaxLoadTimeTab": Axis{
		"",
		"LambdaCal.RpmSp",
		"LambdaCal.MaxLoadTimeTab",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"LambdaCal.MinLoadTab": Axis{
		"",
		"LambdaCal.RpmSp",
		"LambdaCal.MinLoadTab",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"LambdaCal.N_BeforeHW": Axis{
		"",
		"LambdaCal.TempSp",
		"LambdaCal.N_BeforeHW",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"LambdaCal.N_TransDelay": Axis{
		"",
		"LambdaCal.TempSp",
		"LambdaCal.N_TransDelay",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"LambdaCal.PWM_HeatO2FrontSens": Axis{
		"",
		"LambdaCal.HeatRpmSP",
		"LambdaCal.PWM_HeatO2FrontSens",
		"x-axis",
		"rpm",
		"%",
		"",
		"",
	},
	"LambdaCal.PWM_HeatO2RearSens": Axis{
		"",
		"LambdaCal.HeatRpmSP",
		"LambdaCal.PWM_HeatO2RearSens",
		"x-axis",
		"rpm",
		"%",
		"",
		"",
	},
	"LambdaCal.RichStep": Axis{
		"",
		"LambdaCal.U_AdjStepSP",
		"LambdaCal.RichStep",
		"x-axis",
		"mV",
		"%",
		"",
		"",
	},
	"LambdaCal.ST_Enable": Axis{
		"",
		"",
		"LambdaCal.ST_Enable",
		"",
		"",
		"1. Enable closed loop regulation, 0. Disable closed loop regulation",
		"",
		"",
	},
	"LambdaCal.t_HeatFront": Axis{
		"",
		"LambdaCal.HeatRpmSP",
		"LambdaCal.t_HeatFront",
		"x-axis",
		"rpm",
		"s",
		"",
		"",
	},
	"LambdaCal.t_HeatRear": Axis{
		"",
		"LambdaCal.HeatRpmSP",
		"LambdaCal.t_HeatRear",
		"x-axis",
		"rpm",
		"s",
		"",
		"",
	},
	"LambdaCal.TempCthrTab": Axis{
		"",
		"LambdaCal.TempSp",
		"LambdaCal.TempCthrTab",
		"x-axis",
		"°C",
		"°C",
		"",
		"",
	},
	"LambdaCal.TempOthrTab": Axis{
		"",
		"LambdaCal.TempSp",
		"LambdaCal.TempOthrTab",
		"x-axis",
		"°C",
		"°C",
		"",
		"",
	},
	"LimEngCal.TurboSpeedTab": Axis{
		"",
		"LimEngCal.p_AirSP",
		"LimEngCal.TurboSpeedTab",
		"x-axis",
		"Ambient air pressure (kPa)",
		"mg/c",
		"",
		"",
	},
	"LimEngCal.TurboSpeedTab2": Axis{
		"",
		"LimEngCal.n_EngSP",
		"LimEngCal.TurboSpeedTab2",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"LoadCoCal.Q_ACCompAirMap": Axis{
		"LoadCoCal.p_ACSP",
		"LoadCoCal.n_EngineSP",
		"LoadCoCal.Q_ACCompAirMap",
		"Bar",
		"rpm",
		"g/s",
		"",
		"",
	},
	"LoadCoCal.Q_ACDynamicMap": Axis{
		"LoadCoCal.p_ACSP",
		"LoadCoCal.n_EngineSP",
		"LoadCoCal.Q_ACDynamicMap",
		"Bar",
		"rpm",
		"g/s",
		"",
		"",
	},
	"LoadCoCal.Q_ColdFricMap": Axis{
		"LoadCoCal.n_EngXSP",
		"LoadCoCal.T_EngYSP",
		"LoadCoCal.Q_ColdFricMap",
		"rpm",
		"°C",
		"g/s",
		"",
		"",
	},
	"LoadCoCal.Q_DynElLoadTab": Axis{
		"",
		"LoadCoCal.I_LoadSP",
		"LoadCoCal.Q_DynElLoadTab",
		"x-axis",
		"Current Amp",
		"Electric load",
		"",
		"",
	},
	"LoadCoCal.Q_ElLoadCoTab": Axis{
		"",
		"LoadCoCal.n_EngSP",
		"LoadCoCal.Q_ElLoadCoTab",
		"x-axis",
		"rpm",
		"g/s",
		"",
		"",
	},
	"LoadCoCal.t_ACOffDlyTab": Axis{
		"",
		"LoadCoCal.n_EngineSP",
		"LoadCoCal.t_ACOffDlyTab",
		"x-axis",
		"rpm",
		"ms",
		"",
		"",
	},
	"LoadCoCal.t_ACOnDlyTab": Axis{
		"",
		"LoadCoCal.n_EngineSP",
		"LoadCoCal.t_ACOnDlyTab",
		"x-axis",
		"rpm",
		"ms",
		"",
		"",
	},
	"LoadCoCal.t_ElLoadRampTab": Axis{
		"",
		"LoadCoCal.n_EngSP",
		"LoadCoCal.t_ElLoadRampTab",
		"x-axis",
		"rpm",
		"ms",
		"",
		"",
	},
	"MAFCal.Area_Count": Axis{
		"MAFCal.AreaXSP",
		"MAFCal.PQuoteYSP",
		"MAFCal.Area_Count",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MAFCal.cd_ThrottleMap": Axis{
		"MAFCal.AreaXSP",
		"MAFCal.PQuoteYSP",
		"MAFCal.cd_ThrottleMap",
		"mm°",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MAFCal.ConstT_AirInlTab": Axis{
		"",
		"MAFCal.T_EngineSP",
		"MAFCal.ConstT_AirInlTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MAFCal.ConstT_EngineTab": Axis{
		"",
		"MAFCal.T_EngineSP",
		"MAFCal.ConstT_EngineTab",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MAFCal.corr_AirFromp": Axis{
		"MAFCal.Diagn_EngXSP",
		"MAFCal.DiagLoadYSP",
		"MAFCal.corr_AirFromp",
		"rpm",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MAFCal.corr_Count": Axis{
		"MAFCal.Diagn_EngXSP",
		"MAFCal.DiagLoadYSP",
		"MAFCal.corr_Count",
		"rpm",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MAFCal.m_RedundantAirMap": Axis{
		"MAFCal.n_EngXSP",
		"MAFCal.LoadYSP",
		"MAFCal.m_RedundantAirMap",
		"rpm",
		"map",
		"kPa",
		"ActualIn.n_Engine",
		"ActualIn.p_AirInlet",
	},
	"MAFCal.t_NegTransFreezTab": Axis{
		"",
		"MAFCal.n_EngineXSP",
		"MAFCal.t_NegTransFreezTab",
		"x-axis",
		"rpm",
		"ms",
		"",
		"",
	},
	"MAFCal.t_PosTransFreezTab": Axis{
		"",
		"MAFCal.n_EngineXSP",
		"MAFCal.t_PosTransFreezTab",
		"x-axis",
		"rpm",
		"ms",
		"",
		"",
	},
	"MAFCal.WeightConstFuelMap": Axis{
		"MAFCal.n_EngineXSP",
		"MAFCal.p_InletGradYSP",
		"MAFCal.WeightConstFuelMap",
		"Engine speed (%)",
		"Inlet pressure (kPa)",
		"z-axis",
		"",
		"",
	},
	"MaxSpdCal.n_EngLimAir": Axis{
		"",
		"MaxSpdCal.T_EngineSP",
		"MaxSpdCal.n_EngLimAir",
		"x-axis",
		"°C",
		"rpm",
		"",
		"",
	},
	"MissfAdap.MissfCntMap": Axis{
		"MissfCal.m_AirXSP",
		"MissfCal.n_EngYSP",
		"MissfAdap.MissfCntMap",
		"mg/c",
		"rpm",
		"# misfires",
		"",
		"",
	},
	"MissfCal.CatOverheatFactor": Axis{
		"MissfCal.m_AirXSP",
		"MissfCal.n_EngYSP",
		"MissfCal.CatOverheatFactor",
		"mg/c",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"MissfCal.DetectLoadLevel": Axis{
		"MissfCal.T_EngXSP",
		"MissfCal.n_EngYSP",
		"MissfCal.DetectLoadLevel",
		"°C",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"MissfCal.LeanStep": Axis{
		"",
		"LambdaCal.U_AdjStepSP",
		"MissfCal.LeanStep",
		"x-axis",
		"mV",
		"%",
		"",
		"",
	},
	"MissfCal.M_LimTab": Axis{
		"",
		"MissfCal.n_EngineSP",
		"MissfCal.M_LimTab",
		"x-axis",
		"rpm",
		"Nm",
		"",
		"",
	},
	"MissfCal.nrOfTransientFilterCombust": Axis{
		"",
		"MissfCal.EngTempSP",
		"MissfCal.nrOfTransientFilterCombust",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MissfCal.outOfLimDelayMAT": Axis{
		"MissfCal.p_AirAmbOutOfLimSP",
		"MissfCal.T_EngOutOfLimSP",
		"MissfCal.outOfLimDelayMAT",
		"kPa",
		"C",
		"z-axis",
		"",
		"",
	},
	"MissfCal.RichStep": Axis{
		"",
		"LambdaCal.U_AdjStepSP",
		"MissfCal.RichStep",
		"x-axis",
		"mV",
		"%",
		"",
		"",
	},
	"MissfCal.RPMDiffLimMAP": Axis{
		"MissfCal.LoadRPMDiffXSP",
		"MissfCal.n_EngRPMDiffYSP",
		"MissfCal.RPMDiffLimMAP",
		"mg/c",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"MissfCal.startDelayTAB": Axis{
		"",
		"MissfCal.T_EngSP",
		"MissfCal.startDelayTAB",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"MyrtilosAdap.WBLambda_FeedbackMap": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"MyrtilosAdap.WBLambda_FeedbackMap",
		"mg/c",
		"rpm",
		"WBL Lambda feedback",
		"",
		"",
	},
	"MyrtilosAdap.WBLambda_FFMap": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"MyrtilosAdap.WBLambda_FFMap",
		"mg/c",
		"rpm",
		"Active Fueling factor",
		"",
		"",
	},
	"MyrtilosCal.Fuel_GasMap": Axis{
		"BFuelCal.AirXSP",
		"BFuelCal.RpmYSP",
		"MyrtilosCal.Fuel_GasMap",
		"mg/c",
		"rpm",
		"Fuel correction factor",
		"",
		"",
	},
	"MyrtilosCal.Pop_FFacTab": Axis{
		"",
		"MyrtilosCal.Pop_TimeSP",
		"MyrtilosCal.Pop_FFacTab",
		"x-axis",
		"delay(ms)",
		"ExtraFF (1024=100%)",
		"",
		"",
	},
	"MyrtilosCal.Pop_IgnTab": Axis{
		"",
		"MyrtilosCal.Pop_TimeSP",
		"MyrtilosCal.Pop_IgnTab",
		"x-axis",
		"delay(ms)",
		"° BDTC",
		"",
		"",
	},
	"MyrtilosCal.WBL_FFAdjStepTab": Axis{
		"",
		"MyrtilosCal.WBL_LambdaDiffSP",
		"MyrtilosCal.WBL_FFAdjStepTab",
		"x-axis",
		"Diff Lambda vs Target",
		"ExtraFF step",
		"",
		"",
	},
	"O2SPreCal.t_O2SFrontTime": Axis{
		"",
		"O2SPreCal.T_O2SFrontTemp",
		"O2SPreCal.t_O2SFrontTime",
		"x-axis",
		"C",
		"ms",
		"",
		"",
	},
	"PedalMapCal.m_RequestMap": Axis{
		"PedalMapCal.n_EngineMap",
		"PedalMapCal.X_PedalMap",
		"PedalMapCal.m_RequestMap",
		"rpm",
		"% tps",
		"mg/c",
		"",
		"",
	},
	"PedalMapCal.X_AutFacTab": Axis{
		"",
		"PedalMapCal.v_VehAutSP",
		"PedalMapCal.X_AutFacTab",
		"x-axis",
		"km/h",
		"z-axis",
		"",
		"",
	},
	"PedalMapCal.X_CabFacTab": Axis{
		"",
		"PedalMapCal.v_VehManSP",
		"PedalMapCal.X_CabFacTab",
		"x-axis",
		"km/h",
		"z-axis",
		"",
		"",
	},
	"PedalMapCal.X_ManFacTab": Axis{
		"",
		"PedalMapCal.v_VehManSP",
		"PedalMapCal.X_ManFacTab",
		"x-axis",
		"km/h",
		"z-axis",
		"",
		"",
	},
	"PurgeCal.m_AirDerHighTab": Axis{
		"",
		"PurgeCal.m_AirHighSp",
		"PurgeCal.m_AirDerHighTab",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"PurgeCal.m_AirDerLowTab": Axis{
		"",
		"PurgeCal.m_AirHighSp",
		"PurgeCal.m_AirDerLowTab",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"PurgeCal.PdiffMaxRefFlow": Axis{
		"",
		"PurgeCal.p_Diff16XSp",
		"PurgeCal.PdiffMaxRefFlow",
		"x-axis",
		"kPa",
		"mg/s",
		"",
		"",
	},
	"PurgeCal.ValveMap16": Axis{
		"PurgeCal.p_Diff16XSp",
		"PurgeCal.q_Flow16YSp",
		"PurgeCal.ValveMap16",
		"kPa",
		"mg/s",
		"%",
		"",
		"",
	},
	"PurgeCal.ValveMap8": Axis{
		"PurgeCal.p_Diff8XSp",
		"PurgeCal.q_Flow8YSp",
		"PurgeCal.ValveMap8",
		"kPa",
		"mg/s",
		"%",
		"",
		"",
	},
	"PwmLimitCal.PwmLimit": Axis{
		"",
		"PwmLimitCal.U_Batt",
		"PwmLimitCal.PwmLimit",
		"x-axis",
		"V",
		"%",
		"",
		"",
	},
	"QAirDiagCal.HFMOffSim": Axis{
		"",
		"QAirDiagCal.HFMOffSimSP",
		"QAirDiagCal.HFMOffSim",
		"x-axis",
		"g/s",
		"z-axis",
		"",
		"",
	},
	"REPCal.T_AirInletTab": Axis{
		"",
		"REPCal.T_AirInletSP",
		"REPCal.T_AirInletTab",
		"x-axis",
		"°C",
		"kPa",
		"",
		"",
	},
	"SAICal.AltComp": Axis{
		"",
		"SAICal.p_AltCompSP",
		"SAICal.AltComp",
		"x-axis",
		"°C",
		"comb",
		"",
		"",
	},
	"SAICal.FuellingMap": Axis{
		"SAICal.m_AirXSP",
		"SAICal.n_EngineYSP",
		"SAICal.FuellingMap",
		"mg/c",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"SAICal.FuellingMap_2": Axis{
		"SAICal.m_AirXSP",
		"SAICal.n_EngineYSP",
		"SAICal.FuellingMap_2",
		"mg/c",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"SAICal.m_AirInjReq": Axis{
		"",
		"SAICal.T_EngineSP",
		"SAICal.m_AirInjReq",
		"x-axis",
		"°C",
		"mg/c",
		"",
		"",
	},
	"SAICal.m_AirSAIMAP": Axis{
		"SAICal.m_AirXSP",
		"SAICal.p_AltCompSP",
		"SAICal.m_AirSAIMAP",
		"mg/c",
		"kPa",
		"z-axis",
		"",
		"",
	},
	"SAICal.N_ClosedLoopDelay": Axis{
		"",
		"SAICal.T_EngineSP",
		"SAICal.N_ClosedLoopDelay",
		"x-axis",
		"°C",
		"comb",
		"",
		"",
	},
	"SAICal.N_FuellingStart": Axis{
		"",
		"SAICal.p_AltCompSP",
		"SAICal.N_FuellingStart",
		"x-axis",
		"°C",
		"comb",
		"",
		"",
	},
	"SAICal.N_PumpStart": Axis{
		"",
		"SAICal.T_EngineSP",
		"SAICal.N_PumpStart",
		"x-axis",
		"°C",
		"comb",
		"",
		"",
	},
	"SAIDiagCal.m_AirTab": Axis{
		"",
		"SAIDiagCal.m_AirSP",
		"SAIDiagCal.m_AirTab",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"SAIDiagCal.m_WSHAirTab1": Axis{
		"",
		"SAIDiagCal.m_WSHAirSP",
		"SAIDiagCal.m_WSHAirTab1",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"SAIDiagCal.m_WSHAirTab2": Axis{
		"",
		"SAIDiagCal.m_WSHAirSP",
		"SAIDiagCal.m_WSHAirTab2",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"ShiftSupCal.M_HystTab": Axis{
		"",
		"ShiftSupCal.M_RLoadSP",
		"ShiftSupCal.M_HystTab",
		"x-axis",
		"Nm",
		"Nm",
		"",
		"",
	},
	"StartCal.CombFacTab": Axis{
		"",
		"StartCal.T_EngineSP",
		"StartCal.CombFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"StartCal.EnrFacE85Tab": Axis{
		"",
		"StartCal.T_EngineSP",
		"StartCal.EnrFacE85Tab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"StartCal.EnrFacTab": Axis{
		"",
		"StartCal.T_EngineSP",
		"StartCal.EnrFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"StartCal.HighAltFacMap": Axis{
		"StartCal.T_EngineSP",
		"StartCal.p_HighAltSP",
		"StartCal.HighAltFacMap",
		"°C",
		"kPa",
		"z-axis",
		"",
		"",
	},
	"StartCal.m_FuelBefStart": Axis{
		"",
		"StartCal.T_EngineSP",
		"StartCal.m_FuelBefStart",
		"x-axis",
		"°C",
		"mg",
		"",
		"",
	},
	"StartCal.m_ReStBefFuel": Axis{
		"",
		"StartCal.T_EngineSP",
		"StartCal.m_ReStBefFuel",
		"x-axis",
		"°C",
		"mg",
		"",
		"",
	},
	"StartCal.RestartFacTab": Axis{
		"",
		"StartCal.t_RestartSP",
		"StartCal.RestartFacTab",
		"x-axis",
		"sec",
		"z-axis",
		"",
		"",
	},
	"StartCal.ScaleFacRpmE85Map": Axis{
		"StartCal.T_EngineXSP",
		"StartCal.n_EngineYSP",
		"StartCal.ScaleFacRpmE85Map",
		"Temp °C",
		"rpm",
		"Fuelfactor",
		"",
		"",
	},
	"StartCal.ScaleFacRpmMap": Axis{
		"StartCal.T_EngineXSP",
		"StartCal.n_EngineYSP",
		"StartCal.ScaleFacRpmMap",
		"°C",
		"rpm",
		"Fuelfactor",
		"",
		"",
	},
	"SwitchCal.A_AmbPresMap": Axis{
		"SwitchCal.n_EngXSP",
		"SwitchCal.p_AmbientYSP",
		"SwitchCal.A_AmbPresMap",
		"rpm",
		"kPa",
		"mm2",
		"",
		"",
	},
	"SwitchCal.A_SwitchPoint": Axis{
		"SwitchCal.T_Engine",
		"SwitchCal.n_Engine",
		"SwitchCal.A_SwitchPoint",
		"°C",
		"rpm",
		"mm^2",
		"",
		"",
	},
	"SyncCal.n_CombMultiIgnTab": Axis{
		"",
		"SyncCal.T_EngMultiIgnSP",
		"SyncCal.n_CombMultiIgnTab",
		"x-axis",
		"°C",
		"comb",
		"",
		"",
	},
	"TCompCal.EnrFacAutMap": Axis{
		"TCompCal.EnrFacAutXSP",
		"TCompCal.EnrFacAutYSP",
		"TCompCal.EnrFacAutMap",
		"mg/c",
		"y-axis",
		"%",
		"",
		"",
	},
	"TCompCal.EnrFacAutTab": Axis{
		"",
		"TCompCal.T_EngineAutSP",
		"TCompCal.EnrFacAutTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TCompCal.EnrFacE85Map": Axis{
		"TCompCal.EnrFacXSP",
		"TCompCal.EnrFacYSP",
		"TCompCal.EnrFacE85Map",
		"mg/c",
		"y-axis",
		"%",
		"",
		"",
	},
	"TCompCal.EnrFacE85Tab": Axis{
		"",
		"TCompCal.T_EngineAutSP",
		"TCompCal.EnrFacE85Tab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TCompCal.EnrFacMap": Axis{
		"TCompCal.EnrFacXSP",
		"TCompCal.EnrFacYSP",
		"TCompCal.EnrFacMap",
		"mg/c",
		"y-axis",
		"%",
		"",
		"",
	},
	"TCompCal.EnrFacTab": Axis{
		"",
		"TCompCal.T_EngineAutSP",
		"TCompCal.EnrFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TempLimPosCal.Limit": Axis{
		"",
		"TempLimPosCal.Airmass",
		"TempLimPosCal.Limit",
		"x-axis",
		"mg/c",
		"mg/c",
		"",
		"",
	},
	"TempTiCal.map": Axis{
		"TempTiCal.x_axis",
		"TempTiCal.y_axis",
		"TempTiCal.map",
		"kPa",
		"mg/c",
		"ms",
		"",
		"",
	},
	"TEngDiagCal.m_AirperDegA": Axis{
		"TEngDiagCal.T_AirInletSP",
		"TEngDiagCal.n_CombSP",
		"TEngDiagCal.m_AirperDegA",
		"C",
		"C",
		"z-axis",
		"",
		"",
	},
	"TEngDiagCal.m_AirperDegM": Axis{
		"TEngDiagCal.T_AirInletSP",
		"TEngDiagCal.n_CombSP",
		"TEngDiagCal.m_AirperDegM",
		"C",
		"C",
		"z-axis",
		"",
		"",
	},
	"TEngDiagCal.m_LoadFacTAB": Axis{
		"",
		"TEngDiagCal.m_LoadFacSP",
		"TEngDiagCal.m_LoadFacTAB",
		"x-axis",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"TEngDiagCal.T_startSP": Axis{
		"",
		"TEngDiagCal.m_LoadFacSP",
		"TEngDiagCal.T_startSP",
		"x-axis",
		"y-axis",
		"C",
		"",
		"",
	},
	"TorqueCal.a_FreeRollingTab": Axis{
		"",
		"TorqueCal.v_TorqueCalcSP",
		"TorqueCal.a_FreeRollingTab",
		"x-axis",
		"km/h",
		"m/s^2",
		"",
		"",
	},
	"TorqueCal.fi_IgnLimMap": Axis{
		"TorqueCal.m_AirXSP",
		"TorqueCal.n_EngYSP",
		"TorqueCal.fi_IgnLimMap",
		"mg/c",
		"rpm",
		"°",
		"",
		"",
	},
	"TorqueCal.fi_IgnMinTab": Axis{
		"TorqueCal.n_EngMinSP",
		"TorqueCal.T_EngSP",
		"TorqueCal.fi_IgnMinTab",
		"rpm",
		"°C",
		"°",
		"",
		"",
	},
	"TorqueCal.M_1GearTab": Axis{
		"",
		"TorqueCal.n_Eng1GearSP",
		"TorqueCal.M_1GearTab",
		"x-axis",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_5GearLimTab": Axis{
		"",
		"TorqueCal.n_Eng5GearSP",
		"TorqueCal.M_5GearLimTab",
		"x-axis",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.m_AirTorqMap": Axis{
		"TorqueCal.M_EngXSP",
		"TorqueCal.n_EngYSP",
		"TorqueCal.m_AirTorqMap",
		"Nm",
		"rpm",
		"mg/c",
		"",
		"",
	},
	"TorqueCal.M_CabGearLim": Axis{
		"",
		"TorqueCal.n_Eng5GearSP",
		"TorqueCal.M_CabGearLim",
		"x-axis",
		"gear",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_EngMaxAutTab": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_EngMaxAutTab",
		"x-axis",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_EngMaxE85Tab": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_EngMaxE85Tab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueCal.M_EngMaxE85TabAut": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_EngMaxE85TabAut",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueCal.M_EngMaxTab": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_EngMaxTab",
		"x-axis",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_EngTempE85Ta": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_EngTempE85Ta",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueCal.M_EngTempE85Tab": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_EngTempE85Tab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueCal.M_EngTempTab": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_EngTempTab",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueCal.M_IgnInflTorqMap": Axis{
		"TorqueCal.m_AirXSP",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_IgnInflTorqMap",
		"mg/c",
		"rpm",
		"Nm/°",
		"",
		"",
	},
	"TorqueCal.M_ManGearLim": Axis{
		"",
		"",
		"TorqueCal.M_ManGearLim",
		"x-axis",
		"gear",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_NominalMap": Axis{
		"TorqueCal.m_AirXSP",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_NominalMap",
		"mg/c",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_OverBoostTab": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueCal.M_OverBoostTab",
		"x-axis",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_PumpLossMap": Axis{
		"TorqueCal.m_AirPumpXSP",
		"TorqueCal.n_EngPumpYSP",
		"TorqueCal.M_PumpLossMap",
		"mg/c",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.M_ReverseTab": Axis{
		"",
		"TorqueCal.n_EngSP",
		"TorqueCal.M_ReverseTab",
		"x-axis",
		"rpm",
		"Nm",
		"",
		"",
	},
	"TorqueCal.X_AccPedalMap": Axis{
		"PedalMapCal.n_EngineMap",
		"TorqueCal.m_PedYSP",
		"TorqueCal.X_AccPedalMap",
		"rpm",
		"mg/c",
		"%",
		"",
		"",
	},
	"TorqueCal.X_EngTempTab": Axis{
		"",
		"TorqueCal.T_EngTempSP",
		"TorqueCal.X_EngTempTab",
		"x-axis",
		"°C",
		"%",
		"",
		"",
	},
	"TorqueCal.X_IgnEfficTab": Axis{
		"",
		"TorqueCal.fi_MBTOffsYSP",
		"TorqueCal.X_IgnEfficTab",
		"x-axis",
		"",
		"z-axis",
		"",
		"",
	},
	"TorqueTab.m_01": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueTab.m_01",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueTab.m_02": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueTab.m_02",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueTab.m_03": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueTab.m_03",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TorqueTab.m_Actual": Axis{
		"",
		"TorqueCal.n_EngYSP",
		"TorqueTab.m_Actual",
		"x-axis",
		"rpm",
		"z-axis",
		"",
		"",
	},
	"TqToHiCal.Q_AirInletMap": Axis{
		"TqToHiCal.T_AirInletXSP",
		"TqToHiCal.X_AccPedYSP",
		"TqToHiCal.Q_AirInletMap",
		"C",
		"%",
		"g/s",
		"",
		"",
	},
	"TransCal.AccFacMap": Axis{
		"TransCal.AccSP",
		"TransCal.RpmSP",
		"TransCal.AccFacMap",
		"mg/c",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"TransCal.AccIdleTriggLim": Axis{
		"",
		"TransCal.DecTriggSP",
		"TransCal.AccIdleTriggLim",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"TransCal.AccRampFac": Axis{
		"",
		"TransCal.RpmSP",
		"TransCal.AccRampFac",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal.AccTempFacTab": Axis{
		"",
		"TransCal.T_EngineSP",
		"TransCal.AccTempFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal.AccTriggLim": Axis{
		"",
		"TransCal.DecTriggSP",
		"TransCal.AccTriggLim",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"TransCal.DecFacMap": Axis{
		"TransCal.DecSP",
		"TransCal.RpmSP",
		"TransCal.DecFacMap",
		"mg/c",
		"y-axis",
		"z-axis",
		"",
		"",
	},
	"TransCal.DecIdleTriggLim": Axis{
		"",
		"TransCal.DecTriggSP",
		"TransCal.DecIdleTriggLim",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"TransCal.DecRampFac": Axis{
		"",
		"TransCal.RpmSP",
		"TransCal.DecRampFac",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal.DecTempFacTab": Axis{
		"",
		"TransCal.T_EngineSP",
		"TransCal.DecTempFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal.DecTriggLim": Axis{
		"",
		"TransCal.DecTriggSP",
		"TransCal.DecTriggLim",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"TransCal.m_TriggMaxTab": Axis{
		"",
		"TransCal.DecTriggSP",
		"TransCal.m_TriggMaxTab",
		"x-axis",
		"y-axis",
		"mg/c",
		"",
		"",
	},
	"TransCal2.DecrDelayTab": Axis{
		"",
		"TransCal2.T_EngineSP",
		"TransCal2.DecrDelayTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal2.EnrFacE85Tab": Axis{
		"",
		"TransCal2.T_EngineSP",
		"TransCal2.EnrFacE85Tab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal2.EnrFacTab": Axis{
		"",
		"TransCal2.T_EngineSP",
		"TransCal2.EnrFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal3.DecrDelayTab": Axis{
		"",
		"TransCal3.T_EngineSP",
		"TransCal3.DecrDelayTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal3.EnrFacE85Tab": Axis{
		"",
		"TransCal3.T_EngineSP",
		"TransCal3.EnrFacE85Tab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"TransCal3.EnrFacTab": Axis{
		"",
		"TransCal3.T_EngineSP",
		"TransCal3.EnrFacTab",
		"x-axis",
		"°C",
		"z-axis",
		"",
		"",
	},
	"VIOSMAFCal.Q_AirInletTab": Axis{
		"",
		"VIOSMAFCal.TicsSP",
		"VIOSMAFCal.Q_AirInletTab",
		"x-axis",
		"CPUTics: frequency = 13107800/VIOSMAFCal.TicsSP",
		"g/s",
		"",
		"",
	},
	"VIOSMAFCal.Q_AirInletTab2": Axis{
		"",
		"VIOSMAFCal.FreqSP",
		"VIOSMAFCal.Q_AirInletTab2",
		"x-axis",
		"CPUTics: frequency = 13107800/VIOSMAFCal.TicsSP",
		"g/s",
		"",
		"",
	},
	"X_AccPedalAutTAB": Axis{
		"",
		"X_AccPedalAutSP",
		"X_AccPedalAutTAB",
		"x-axis",
		"AD",
		"%",
		"",
		"",
	},
	"X_AccPedalManTAB": Axis{
		"",
		"X_AccPedalManSP",
		"X_AccPedalManTAB",
		"x-axis",
		"AD",
		"%",
		"",
		"",
	},
}
