name: Build Linux Develop

on:
  push:
    branches:
    - 'master'
    - 'develop'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Set up Go
      uses: actions/setup-go@v6.4.0
      with:
        go-version: '1.26.4'
        cache: false
    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install 7zip gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libusb-1.0-0-dev libgtk-3-dev libasound2-dev libftdi1 libftdi1-dev
    - name: Get Go dependencies
      run: go get .
    - name: Build j2534proxy
      run: make j2534proxy
    - name: Build txlogger
      run: make txlogger
