name: Build Linux Release

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.2
    - name: Set up Go
      uses: actions/setup-go@v6.4.0
      with:
        go-version: '1.26.4'
        cache: false
    - name: Get dependencies
      run: sudo apt-get update && sudo apt-get install 7zip gcc libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev libusb-1.0-0-dev libgtk-3-dev libasound2-dev libftdi1 libftdi1-dev
    - name: Install Kvaser CANLIB
      run: |
        wget -qO- "https://www.kvaser.com/downloads-kvaser/?utm_source=software&utm_ean=7330130980754&utm_status=latest" | tar xz
        make -C linuxcan/canlib
        sudo make -C linuxcan/canlib install
    - name: Get Go dependencies
      run: go get .
    - name: Build txlogger
      run: make txlogger
    - name: Build AppImage
      run: make appimage
    - name: Archive
      run: 7z a txloger_ubuntu_x64.7z txlogger
    - name: Release
      uses: softprops/action-gh-release@v3
      if: github.ref_type == 'tag'
      env:
        GITHUB_REPOSITORY: roffe/txlogger
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        make_latest: "true"
        files: |
          txloger_ubuntu_x64.7z
          txlogger-*-x86_64.AppImage
