# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Build Windows Develop
on:
  push:
    branches:
    - 'master'
    

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: windows-latest
            vcpkgCommitId: '74e6536215718009aae747d86d84b78376bf9e09'
    steps:
   
    - uses: actions/checkout@v5
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.25.3'
        cache: false
    - name: Install dependencies
      run: |
        go get .
        go install fyne.io/tools/cmd/fyne@latest
        .\setup_build_env.ps1
    

    - name: Build
      env:
        FOO: "BAR"
      run: |
        $env:PATH += ";D:\a\txlogger\txlogger\llvm-mingw\bin"
        $env:PATH
        .\build.ps1 -cangateway -txlogger

